import type { Metadata } from "next";
import { InformationPage } from "@/components/information-page";

export const metadata: Metadata = {
  title: "Privacidad",
  description: "Cómo Oportunia trata datos y preferencias durante el uso del sitio.",
  alternates: { canonical: "/privacidad" },
};

export default function PrivacyPage() {
  return <InformationPage eyebrow="TU INFORMACIÓN" title="Política de privacidad" intro="Explicamos qué información usa Oportunia y qué integraciones permanecen cerradas hasta contar con configuración y consentimiento válidos." updated="21 de septiembre de 2026"><section><h2>Identificación del responsable</h2><p>La identificación legal y el canal formal se publicarán cuando estén verificados. No publicamos nombres, RUC ni correos ficticios.</p></section><section><h2>Analítica propia y datos tratados</h2><p>Para medir el recorrido desde campañas de TikTok, Oportunia registra los eventos <code>landing_view</code>, <code>detail_view</code>, <code>official_click</code> y <code>engagement</code>, junto con el identificador de la oportunidad y los parámetros UTM presentes en la URL. Un <code>sessionId</code> opaco y aleatorio se guarda en <code>sessionStorage</code> durante la sesión del navegador; no es un identificador persistente entre sesiones. <code>engagementMs</code> mide tiempo visible en la ficha y cada evento se limita a un valor entre 250 y 60 000 milisegundos.</p><p>Esta analítica propia no recopila dirección IP, correo, user-agent ni fingerprint. La infraestructura de alojamiento puede procesar datos técnicos necesarios para seguridad y entrega de la página, de forma separada de esta medición.</p></section><section><h2>Finalidades</h2><p>Usamos estos eventos para conocer de forma agregada qué campañas llevan a visitas, vistas de detalle y aperturas de fuentes oficiales, medir interacción y detectar tráfico anómalo. Las oportunidades guardadas y las preferencias de alerta se conservan localmente para recordar tus elecciones en el dispositivo.</p></section><section><h2>Google Analytics y publicidad</h2><p>GA4 y Google AdSense permanecen desactivados mientras falte una configuración válida o el consentimiento correspondiente. Si se habilita GA4 después de tu consentimiento, Google puede procesar datos de medición conforme a su propia política de privacidad. AdSense también exige configuración y habilitación internas válidas.</p></section><section><h2>Tus decisiones</h2><p>Puedes borrar los datos locales desde la configuración de tu navegador y retirar o revocar el consentimiento mediante la CMP. La revocación desactiva GA4 y evita futuros eventos de esa integración; no borra ni elimina de forma retroactiva datos que Google ya pudiera haber procesado.</p></section></InformationPage>;
}
