import type { Metadata } from "next";
import { InformationPage } from "@/components/information-page";

export const metadata: Metadata = {
  title: "Cookies",
  description: "Cookies, almacenamiento local y consentimiento publicitario en Oportunia.",
  alternates: { canonical: "/cookies" },
};

export default function CookiesPage() {
  return <InformationPage eyebrow="CONTROL EN TUS MANOS" title="Cookies y almacenamiento local" intro="Oportunia limita el almacenamiento y mantiene GA4 y la publicidad desactivados hasta contar con configuración y consentimiento válidos." updated="21 de septiembre de 2026"><section><h2>Almacenamiento en tu dispositivo</h2><p>Las oportunidades guardadas y las preferencias de alerta usan almacenamiento local del navegador. Para la analítica propia de campañas de TikTok se guarda en <code>sessionStorage</code> un <code>sessionId</code> opaco y aleatorio que termina con la sesión del navegador. Sirve para agrupar los eventos <code>landing_view</code>, <code>detail_view</code>, <code>official_click</code> y <code>engagement</code>. Este último incluye <code>engagementMs</code>, acotado entre 250 y 60 000 milisegundos por evento.</p><p>Esta analítica propia se usa para atribución y medición agregada de campañas; no recopila IP, correo, user-agent ni fingerprint.</p></section><section><h2>Cookies esenciales</h2><p>Las áreas editoriales protegidas pueden usar cookies de sesión necesarias para autenticar al equipo autorizado. No se usan para publicidad dirigida.</p></section><section><h2>GA4, AdSense y consentimiento</h2><p>GA4 y AdSense permanecen desactivados si falta la configuración válida o el consentimiento correspondiente. Un estado desconocido, rechazado o con error no abre el gate. Si se habilita GA4, Google puede procesar datos de medición según su política de privacidad.</p><p>La CMP certificada de Google se configura fuera de este repositorio. Oportunia no presenta un banner propio como reemplazo de esa CMP. La integración técnica acepta la señal conservadora <code>oportunia:ads-consent</code> únicamente después de que la CMP externa haya resuelto la elección.</p></section><section><h2>Cómo retirar tus preferencias</h2><p>Puedes eliminar datos locales y cookies desde la configuración del navegador y retirar o revocar el consentimiento mediante la CMP. Desde ese momento se desactiva GA4 y se impiden futuros eventos de esa integración; la revocación no elimina retroactivamente datos que Google ya pudiera haber procesado.</p></section></InformationPage>;
}
