import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Bookmark, ExternalLink, Search, ShieldCheck } from "lucide-react";
import { Footer, Header } from "@/components/portal";

export const metadata: Metadata = { title: "Cómo funciona | Oportunia", description: "Información clara, fuentes oficiales y fechas visibles para encontrar tu próximo paso en Perú." };

export default function HowItWorksPage() {
  return <><Header /><main className="how-page container"><div className="how-intro"><p className="eyebrow">MENOS INCERTIDUMBRE. MÁS POSIBILIDADES.</p><h1>Encontrar tu próximo paso<br />debería ser más simple.</h1><p>Oportunia reúne empleos, prácticas y programas en Perú con la información que necesitas para decidir y postular a tiempo.</p></div><div className="how-grid">{[{ icon: Search, step: "01", title: "Encuentra lo que va contigo.", text: "Busca por carrera, puesto o entidad. Filtra por región, modalidad y nivel para dar con una oportunidad relevante." }, { icon: ShieldCheck, step: "02", title: "Decide con información.", text: "Revisa la fecha de cierre, los requisitos y el bloque Antes de postular. Las fichas de ejemplo están identificadas y no se presentan como verificadas." }, { icon: ExternalLink, step: "03", title: "Da el siguiente paso.", text: "Consulta las bases y postula en la web oficial de la entidad. No recibimos postulaciones ni cobramos a quienes buscan una oportunidad." }].map(({ icon: Icon, step, title, text }) => <section className="how-card" key={step}><div><span className="feature-icon"><Icon size={25} /></span><span className="step-number">{step}</span></div><h2>{title}</h2><p>{text}</p></section>)}</div><section className="how-promise"><Bookmark size={35} /><div><h2>Las oportunidades pasan.<br />Que no se te pasen.</h2><p>Guarda las fichas que te interesan en tu navegador. También puedes configurar preferencias locales de alertas; el envío de notificaciones todavía no está habilitado.</p><Link className="button button-primary" href="/">Explorar oportunidades <ArrowRight size={17} /></Link></div></section><section className="editorial-principles"><p className="eyebrow">NUESTRO COMPROMISO</p><h2>Tu confianza, primero.</h2><p>Una convocatoria real publicada debe tener fuente oficial, fecha de cierre, información del perfil y responsable editorial. Los plazos vencidos se muestran como cerrados. Siempre contrasta la información con las bases, porque la entidad puede actualizar sus condiciones.</p><p>Este catálogo inicial contiene ejemplos editoriales para mostrar la experiencia. No confundimos un ejemplo con una oportunidad verificada.</p></section></main><Footer /></>;
}
